"""
Ask DemandPulse — conversational access to the forecasting model.
pages/02_Ask_DemandPulse.py

The assistant answers by CALLING the trained model, never by guessing. Every
number in a reply came out of a tool call you can inspect under "sources".
"""

import os
import sys
from datetime import date

import streamlit as st

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from ml.chat_agent import answer                     # noqa: E402
from ml.llm import LLMUnavailable                    # noqa: E402
from pages._llm_sidebar import llm_sidebar           # noqa: E402

st.set_page_config(page_title="Ask DemandPulse", page_icon="💬", layout="wide")

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
html,body,[class*="css"]{font-family:'Inter',sans-serif}
.hero{background:linear-gradient(135deg,#0d1b2a 0%,#1b263b 100%);border-radius:18px;
  padding:22px 26px;color:white;margin-bottom:18px}
.hero h1{margin:0;font-size:23px;font-weight:600}
.hero p{margin:6px 0 0;opacity:.65;font-size:13px}
.srcbox{background:rgba(255,255,255,.04);border-left:3px solid #4A90D9;border-radius:8px;
  padding:8px 12px;margin:4px 0;color:rgba(255,255,255,.75);font-size:12px;font-family:monospace}
section[data-testid="stSidebar"]{background:rgba(13,27,42,.97)!important}
section[data-testid="stSidebar"] *{color:white!important}
</style>
""", unsafe_allow_html=True)

st.markdown("""
<div class="hero">
  <h1>💬 Ask DemandPulse</h1>
  <p>Ask about demand in plain language. Answers are generated by calling the trained
     forecasting model — the assistant is not allowed to invent numbers.</p>
</div>
""", unsafe_allow_html=True)

llm = llm_sidebar()

with st.sidebar:
    st.markdown("---")
    st.markdown("### 🧭 What it can answer")
    st.caption(
        "• demand for a city / date / format\n\n"
        "• a week or month ahead\n\n"
        "• which events are driving a spike\n\n"
        "• how accurate the model is\n\n"
        "It cannot see your own sales, menu or competitors.")
    if st.button("🗑️ Clear conversation", use_container_width=True):
        st.session_state.pop("chat", None)
        st.session_state.pop("history", None)
        st.rerun()

if not llm["available"]:
    st.warning(
        "**No language model connected yet.** The forecasting model works fine "
        "without one — only this chat layer needs it. Two options:\n\n"
        "**Ollama** — free, runs on your machine, no API key: install from "
        "[ollama.com](https://ollama.com/download), then `ollama pull qwen2.5:7b` "
        "and `ollama serve`.\n\n"
        "**GPT-4** — set `OPENAI_API_KEY` and `DEMANDPULSE_LLM_MODEL=gpt-4o`.\n\n"
        "Setup commands are in the sidebar. Meanwhile, the Restaurant Impact page "
        "gives you the same forecasts without the conversation.")

SUGGESTIONS = [
    "What does Diwali week look like for a cloud kitchen in Bengaluru?",
    "Should I add staff at my Mumbai pub next weekend?",
    "Which day next month is busiest for a cafe in Pune?",
    "Why is demand down in Delhi in early October?",
]

if "chat" not in st.session_state:
    st.session_state.chat = []
    st.session_state.history = []

if not st.session_state.chat:
    st.markdown("**Try one of these:**")
    cols = st.columns(2)
    for i, s in enumerate(SUGGESTIONS):
        if cols[i % 2].button(s, key=f"sug{i}", use_container_width=True):
            st.session_state.pending = s
            st.rerun()

for msg in st.session_state.chat:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg.get("trace"):
            with st.expander(f"🔍 sources — {len(msg['trace'])} model call(s)"):
                for t in msg["trace"]:
                    err = f"  ⚠️ {t['error']}" if t.get("error") else ""
                    st.markdown(
                        f"<div class='srcbox'>{t['tool']}({t['input']}){err}</div>",
                        unsafe_allow_html=True)

prompt = st.chat_input("Ask about demand…") or st.session_state.pop("pending", None)

if prompt:
    st.session_state.chat.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)
    with st.chat_message("assistant"):
        if not llm["available"]:
            msg = ("I can't answer yet — no language model is connected. "
                   "Run Ollama locally (free, no key) or set an OpenAI/Anthropic key; "
                   "the sidebar has the exact commands. The forecasts themselves are "
                   "unaffected — the Restaurant Impact page still works.")
            st.warning(msg)
            st.session_state.chat.append({"role": "assistant", "content": msg})
        else:
            with st.spinner("Consulting the forecast model…"):
                try:
                    res = answer(prompt, history=st.session_state.history)
                    st.markdown(res["text"])
                    st.session_state.history = res["messages"] + [
                        {"role": "assistant", "content": res["text"]}]
                    st.session_state.chat.append(
                        {"role": "assistant", "content": res["text"],
                         "trace": res["tool_trace"]})
                    if res["tool_trace"]:
                        with st.expander(f"🔍 sources — {len(res['tool_trace'])} model call(s)"):
                            for t in res["tool_trace"]:
                                err = f"  ⚠️ {t['error']}" if t.get("error") else ""
                                st.markdown(
                                    f"<div class='srcbox'>{t['tool']}({t['input']}){err}</div>",
                                    unsafe_allow_html=True)
                except LLMUnavailable as exc:
                    st.error(str(exc))
                except Exception as exc:                          # noqa: BLE001
                    st.error(f"Something went wrong: {exc}")

st.caption(f"Model-backed answers · {date.today().isoformat()} · "
           "figures come from the LightGBM forecaster, not the language model.")
